[package]
name = "gibblox-core"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[features]
default = []
std = ["erofs-rs/std"]

[dependencies]
async-trait = "0.1.89"
erofs-rs = { path = "../../erofs-rs/erofs", default-features = false }
tracing = { version = "0.1.41", default-features = false, features = ["attributes"] }

[dev-dependencies]
futures = { version = "0.3.31", default-features = false, features = ["executor"] }
gibblox-cache = { path = "../gibblox-cache" }
gibblox-file = { path = "../gibblox-file" }
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt"] }

[[example]]
name = "erofs_cat"
required-features = ["std"]
path = "../../examples/erofs_cat.rs"
